import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { Users, Coins, TrendingUp, RefreshCw, Package, ShoppingBag, ShieldCheck, BriefcaseBusiness, Radio, AlertTriangle, RotateCcw, ArrowDownToLine, Settings, Activity } from "lucide-react";
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { AdminLayout } from "./AdminLayout";
import { useAdmin } from "@/context/AdminContext";

type Stats = { userCount:number; newUsersToday:number; newUsersWeek:number; activeListings:number; orderCount:number; salesToday:number; gmv:number; gmvToday:number; buyerProtection:number; businessFees:number; openDisputes:number; totalDisputes:number; openReturns:number; refunds:number; activeLiveStreams:number; liveViewers:number; creditsIssued:number; creditsSpent:number; salesTrend:Array<{label:string;date:string;orders:number;gmv:number}>; userTrend:Array<{label:string;users:number}>; recentPayments:Array<{id:string;email:string;amount:number;currency:string;date:string;status:string}> };
const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(n||0);
const num=(n:number)=>new Intl.NumberFormat("en-GB").format(n||0);

export function AdminDashboardPage(){
 const {isAdmin,authFetch}=useAdmin(); const [,go]=useLocation(); const [s,setS]=useState<Stats|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!isAdmin){go("/admin");return;} load();},[isAdmin]);
 async function load(){setLoading(true);try{const r=await authFetch("/api/admin/stats");if(r.ok)setS(await r.json());}finally{setLoading(false)}}
 const cards=s?[
  ["GMV",money(s.gmv),`Today ${money(s.gmvToday)}`,TrendingUp], ["Sales today",num(s.salesToday),`${num(s.orderCount)} orders total`,ShoppingBag],
  ["Active listings",num(s.activeListings),"Currently for sale",Package], ["New users",num(s.newUsersToday),`${num(s.newUsersWeek)} in 7 days`,Users],
  ["Buyer Protection",money(s.buyerProtection),"Collected from buyers",ShieldCheck], ["Business fees",money(s.businessFees),"Seller fees earned",BriefcaseBusiness],
  ["Credits issued",`${num(s.creditsIssued)} cr`,"Ledger-recorded credits",Coins], ["Credits spent",`${num(s.creditsSpent)} cr`,"Ledger-recorded spend",Coins],
  ["Live streams",num(s.activeLiveStreams),`${num(s.liveViewers)} current viewers`,Radio], ["Open disputes",num(s.openDisputes),`${num(s.totalDisputes)} total`,AlertTriangle],
  ["Open returns",num(s.openReturns),"Awaiting completion",RotateCcw], ["Refunds",money(s.refunds),"Recorded dispute/return refunds",RotateCcw],
 ] as const:[];
 return <AdminLayout><div className="space-y-6">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h1 className="break-all text-xl sm:text-2xl font-black text-gray-900">Admin Overview 2.0</h1><p className="text-sm text-gray-500 mt-1">Marketplace health, revenue and activity from Bazunk's own records.</p></div><button onClick={load} disabled={loading} className="flex shrink-0 items-center justify-center gap-2 self-start px-4 py-2 rounded-xl bg-gray-900 text-white text-sm font-bold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>
  {loading&&!s?<div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{Array.from({length:12}).map((_,i)=><div key={i} className="h-28 bg-white rounded-2xl animate-pulse"/>)}</div>:s&&<>
   <div className="grid grid-cols-1 min-[390px]:grid-cols-2 xl:grid-cols-4 gap-3 sm:gap-4">{cards.map(([label,value,sub,Icon])=><div key={label} className="min-w-0 overflow-hidden bg-white border border-gray-100 shadow-sm rounded-2xl p-4 sm:p-5"><div className="flex min-w-0 items-start justify-between gap-2 mb-3"><span className="min-w-0 break-words text-[11px] sm:text-xs font-bold uppercase tracking-wide text-gray-400">{label}</span><Icon className="w-5 h-5 text-[#F26B21]"/></div><div className="text-2xl font-black text-gray-900">{value}</div><div className="text-xs text-gray-400 mt-1">{sub}</div></div>)}</div>
   <div className="grid min-w-0 lg:grid-cols-2 gap-5"><div className="min-w-0 bg-white border rounded-2xl p-3 sm:p-5"><h2 className="font-black text-gray-900">7-day sales & GMV</h2><p className="text-xs text-gray-400 mb-4">Completed marketplace activity excluding cancelled/refunded orders.</p><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={s.salesTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(v:any,n:any)=>n==='gmv'?[money(Number(v)),'GMV']:[v,'Orders']}/><Line type="monotone" dataKey="gmv" stroke="#F26B21" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div>
   <div className="bg-white border rounded-2xl p-5"><h2 className="font-black text-gray-900">New users · 30 days</h2><p className="text-xs text-gray-400 mb-4">Daily registrations.</p><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={s.userTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" interval={4}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="users" fill="#4A5CE8" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div></div>
   <div><h2 className="text-sm font-black text-gray-500 uppercase tracking-wide mb-3">Operations</h2><div className="grid grid-cols-1 min-[390px]:grid-cols-2 md:grid-cols-4 gap-3">{[["Orders","/admin/orders",ShoppingBag],["Importer Control","/admin/importer-control",Activity],["Credits Economy","/admin/credits-economy",Coins],["Settings","/admin/settings",Settings]].map(([label,href,Icon]:any)=><button key={href} onClick={()=>go(href)} className="bg-white border rounded-2xl p-4 flex items-center gap-3 hover:border-[#F26B21]"><Icon className="w-5 h-5 text-[#F26B21]"/><span className="font-bold text-sm">{label}</span></button>)}</div></div>
   <div className="bg-white border rounded-2xl overflow-hidden"><div className="px-5 py-4 border-b"><h2 className="font-black">Recent Stripe payments</h2></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 text-left text-xs uppercase text-gray-400"><th className="p-3">Customer</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Date</th></tr></thead><tbody>{s.recentPayments.length?s.recentPayments.map(p=><tr key={p.id} className="border-t"><td className="p-3">{p.email}</td><td className="p-3 font-bold">{p.currency} {p.amount.toFixed(2)}</td><td className="p-3">{p.status}</td><td className="p-3">{new Date(p.date).toLocaleString("en-GB")}</td></tr>):<tr><td colSpan={4} className="p-8 text-center text-gray-400">No recent Stripe payments</td></tr>}</tbody></table></div></div>
  </>}
 </div></AdminLayout>
}
