import { useEffect,useMemo,useState } from "react";
import { AdminLayout } from "./AdminLayout";
import { useAdmin } from "@/context/AdminContext";
import { Flag, Search, ShieldCheck } from "lucide-react";
type F={key:string;label:string;group:string;enabled:boolean};
export function AdminFeatureFlagsPage(){
 const { token }=useAdmin() as any; const [flags,setFlags]=useState<F[]>([]); const [q,setQ]=useState(""); const [busy,setBusy]=useState<string|null>(null);
 const load=()=>fetch('/api/admin/feature-flags',{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(setFlags);
 useEffect(()=>{load()},[]);
 const groups=useMemo(()=>{const m=new Map<string,F[]>(); flags.filter(f=>(f.label+' '+f.group).toLowerCase().includes(q.toLowerCase())).forEach(f=>m.set(f.group,[...(m.get(f.group)||[]),f]));return [...m.entries()]},[flags,q]);
 async function toggle(f:F){setBusy(f.key);try{const r=await fetch(`/api/admin/feature-flags/${f.key}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({enabled:!f.enabled})});if(!r.ok)throw new Error();setFlags(x=>x.map(a=>a.key===f.key?{...a,enabled:!a.enabled}:a));window.dispatchEvent(new Event('bazunk-settings-updated'));}finally{setBusy(null)}}
 return <AdminLayout><div className="max-w-6xl mx-auto space-y-5"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Flag className="w-6 h-6 text-[#F26B21]"/>Feature Flags</h1><p className="text-sm text-gray-500 mt-1">Switch marketplace modules on or off instantly without deleting code, data or redeploying.</p></div><div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-sm text-amber-900 flex gap-2"><ShieldCheck className="w-5 h-5 shrink-0"/>Turning a feature off hides/blocks its public route and protected API where supported. Existing records remain intact and become available again when re-enabled.</div><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search features..." className="w-full pl-9 pr-3 py-2 border rounded-xl bg-white"/></div>{groups.map(([group,items])=><section key={group} className="bg-white rounded-2xl border shadow-sm overflow-hidden"><div className="px-5 py-3 bg-gray-50 border-b font-semibold">{group}</div><div className="divide-y">{items.map(f=><div key={f.key} className="px-5 py-4 flex items-center justify-between gap-4"><div><div className="font-semibold">{f.label}</div><div className="text-xs text-gray-500 font-mono">{f.key}</div></div><div className="flex items-center gap-3"><span className={`text-xs font-semibold ${f.enabled?'text-emerald-600':'text-red-600'}`}>{f.enabled?'ON':'OFF'}</span><button disabled={busy===f.key} onClick={()=>toggle(f)} aria-label={`Turn ${f.label} ${f.enabled?'off':'on'}`} className={`relative w-12 h-7 rounded-full transition ${f.enabled?'bg-emerald-500':'bg-gray-300'} disabled:opacity-50`}><span className={`absolute top-1 w-5 h-5 bg-white rounded-full shadow transition-all ${f.enabled?'left-6':'left-1'}`}/></button></div></div>)}</div></section>)}</div></AdminLayout>
}
