import { useState, useEffect } from "react";
import { Shield, AlertTriangle, Clock, CheckCircle2, XCircle, ChevronDown, RefreshCw, CreditCard, Coins, SearchCheck, Ban } from "lucide-react";
import { AdminLayout } from "./AdminLayout";
import { useAdmin } from "@/context/AdminContext";

const REASON_LABELS: Record<string,string>={item_not_received:"Item Not Received",not_as_described:"Not As Described",damaged:"Damaged in Transit",wrong_item:"Wrong Item Sent",other:"Other"};
const STATUS_META:Record<string,{label:string;color:string;icon:React.ElementType}>={open:{label:"Open",color:"bg-amber-100 text-amber-700",icon:AlertTriangle},under_review:{label:"Under Review",color:"bg-blue-100 text-blue-700",icon:Clock},resolved_refund:{label:"Refund Issued",color:"bg-emerald-100 text-emerald-700",icon:CheckCircle2},resolved_no_action:{label:"No Action",color:"bg-gray-100 text-gray-600",icon:XCircle},closed:{label:"Closed",color:"bg-gray-100 text-gray-400",icon:XCircle}};
type Dispute={id:string;order_id:string|null;buyer_email:string;seller_email:string|null;item_title:string;reason:string;description:string;status:string;resolution_notes:string|null;refund_amount:string|null;seller_response:string|null;created_at:string;resolved_at:string|null;order_price:string|null;buyer_protection_fee:string|null;order_status:string|null;has_stripe_payment:boolean};

export function AdminDisputesPage(){
 const {token}=useAdmin(); const [disputes,setDisputes]=useState<Dispute[]>([]); const [loading,setLoading]=useState(true); const [expanded,setExpanded]=useState<string|null>(null); const [busy,setBusy]=useState<string|null>(null); const [notes,setNotes]=useState<Record<string,string>>({}); const [partial,setPartial]=useState<Record<string,string>>({}); const [credits,setCredits]=useState<Record<string,string>>({}); const [error,setError]=useState<Record<string,string>>({});
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/disputes",{headers:{Authorization:`Bearer ${token}`}});if(r.ok)setDisputes(await r.json());}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function act(d:Dispute,action:string,payload:Record<string,unknown>={}){const label=action==="refund_full"?"issue a FULL refund":action==="refund_partial"?`issue a PARTIAL refund of £${partial[d.id]||"0"}`:action==="credits"?`add ${credits[d.id]||"0"} credits to the buyer`:action==="no_action"?"resolve with no refund":action==="close"?"close this dispute":"mark this dispute under review";if(!confirm(`Confirm: ${label}?\n\nThis action will be recorded in the admin audit log.`))return;setBusy(d.id);setError(x=>({...x,[d.id]:""}));try{const r=await fetch(`/api/admin/disputes/${d.id}/action`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({action,notes:notes[d.id]||"",amount:Number(partial[d.id]||0),credits:Number(credits[d.id]||0),...payload})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Action failed");await load();}catch(e:any){setError(x=>({...x,[d.id]:e.message||"Action failed"}))}finally{setBusy(null)}}
 const open=disputes.filter(d=>d.status==="open").length,review=disputes.filter(d=>d.status==="under_review").length;
 return <AdminLayout><div className="p-6 max-w-6xl mx-auto"><div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-black text-gray-900">Dispute Resolution</h1><p className="text-sm text-gray-500 mt-0.5">Review evidence, refund payments, award credits and resolve buyer/seller disputes</p></div><button onClick={load} className="flex items-center gap-2 px-4 py-2 rounded-xl border border-gray-200 text-sm font-semibold text-gray-600"><RefreshCw className="w-4 h-4"/>Refresh</button></div>
 <div className="grid grid-cols-3 gap-4 mb-6">{[["Open",open,"text-amber-600 bg-amber-50"],["Under Review",review,"text-blue-600 bg-blue-50"],["Total",disputes.length,"text-gray-700 bg-gray-50"]].map(([l,v,c])=><div key={String(l)} className={`${c} rounded-2xl p-4`}><p className="text-2xl font-black">{v}</p><p className="text-sm text-gray-500">{l}</p></div>)}</div>
 {loading?<div className="text-center py-16 text-gray-400">Loading…</div>:disputes.length===0?<div className="text-center py-16 text-gray-400"><Shield className="w-12 h-12 mx-auto mb-3"/><p>No disputes yet</p></div>:<div className="space-y-3">{disputes.map(d=>{const m=STATUS_META[d.status]||STATUS_META.open,isOpen=expanded===d.id,total=Number(d.order_price||0)+Number(d.buyer_protection_fee||0);return <div key={d.id} className="bg-white rounded-2xl border border-gray-100 overflow-hidden"><button onClick={()=>setExpanded(isOpen?null:d.id)} className="w-full flex items-center gap-4 p-4 text-left hover:bg-gray-50"><span className={`flex items-center gap-1.5 text-xs font-bold px-2.5 py-1 rounded-full ${m.color}`}><m.icon className="w-3 h-3"/>{m.label}</span><div className="flex-1 min-w-0"><p className="font-semibold text-gray-900 text-sm truncate">{d.item_title}</p><p className="text-xs text-gray-400">{REASON_LABELS[d.reason]||d.reason} · {d.buyer_email}</p></div><p className="text-xs text-gray-400">{new Date(d.created_at).toLocaleDateString("en-GB")}</p><ChevronDown className={`w-4 h-4 ${isOpen?"rotate-180":""}`}/></button>{isOpen&&<div className="border-t p-5 space-y-5">
 <div className="grid md:grid-cols-3 gap-4 text-sm"><div><p className="text-xs text-gray-400">Buyer</p><p className="font-medium">{d.buyer_email}</p></div><div><p className="text-xs text-gray-400">Seller</p><p className="font-medium">{d.seller_email||"—"}</p></div><div><p className="text-xs text-gray-400">Order</p><p className="font-medium">{d.order_id||"—"}</p></div><div><p className="text-xs text-gray-400">Order value</p><p className="font-medium">£{total.toFixed(2)}</p></div><div><p className="text-xs text-gray-400">Payment</p><p className="font-medium">{d.has_stripe_payment?"Stripe payment":"No Stripe payment"}</p></div><div><p className="text-xs text-gray-400">Order status</p><p className="font-medium capitalize">{d.order_status||"—"}</p></div></div>
 <div className="bg-gray-50 rounded-xl p-3"><p className="text-xs text-gray-400 mb-1">Buyer's description</p><p className="text-sm">{d.description}</p></div>{d.seller_response&&<div className="bg-blue-50 rounded-xl p-3"><p className="text-xs text-blue-400">Seller's response</p><p className="text-sm text-blue-800">{d.seller_response}</p></div>}
 {d.resolution_notes&&<div className="bg-emerald-50 rounded-xl p-3"><p className="text-xs text-emerald-600">Previous resolution note</p><p className="text-sm">{d.resolution_notes}</p></div>}
 <div className="border-t pt-4"><p className="text-xs font-bold text-gray-500 uppercase tracking-wide mb-3">Resolution centre</p><textarea rows={2} value={notes[d.id]||""} onChange={e=>setNotes(x=>({...x,[d.id]:e.target.value}))} placeholder="Admin/resolution notes (recommended)" className="w-full px-3 py-2 rounded-xl border border-gray-200 text-sm mb-3"/>
 <div className="grid md:grid-cols-2 gap-3">
  <button disabled={busy===d.id} onClick={()=>act(d,"refund_full")} className="p-4 rounded-xl border border-emerald-200 bg-emerald-50 text-left disabled:opacity-50"><div className="flex gap-2 font-bold text-emerald-800"><CreditCard className="w-5 h-5"/>Full refund</div><p className="text-xs text-emerald-700 mt-1">Refund all remaining Stripe payment to the buyer.</p></button>
  <div className="p-4 rounded-xl border border-green-200"><div className="font-bold text-gray-800 mb-2">Partial refund</div><div className="flex gap-2"><input type="number" min="0.01" step="0.01" value={partial[d.id]||""} onChange={e=>setPartial(x=>({...x,[d.id]:e.target.value}))} placeholder="£ amount" className="min-w-0 flex-1 px-3 py-2 rounded-lg border"/><button disabled={busy===d.id} onClick={()=>act(d,"refund_partial")} className="px-4 py-2 bg-green-600 text-white rounded-lg font-semibold">Refund</button></div></div>
  <div className="p-4 rounded-xl border border-violet-200"><div className="flex gap-2 font-bold text-gray-800 mb-2"><Coins className="w-5 h-5 text-violet-600"/>Goodwill credits</div><div className="flex gap-2"><input type="number" min="1" step="1" value={credits[d.id]||""} onChange={e=>setCredits(x=>({...x,[d.id]:e.target.value}))} placeholder="Credits" className="min-w-0 flex-1 px-3 py-2 rounded-lg border"/><button disabled={busy===d.id} onClick={()=>act(d,"credits")} className="px-4 py-2 bg-violet-600 text-white rounded-lg font-semibold">Add</button></div></div>
  <div className="p-4 rounded-xl border border-blue-200 flex gap-2"><button disabled={busy===d.id} onClick={()=>act(d,"mark_review")} className="flex-1 px-3 py-2 rounded-lg bg-blue-50 text-blue-700 font-semibold flex items-center justify-center gap-2"><SearchCheck className="w-4 h-4"/>Under review</button><button disabled={busy===d.id} onClick={()=>act(d,"no_action")} className="flex-1 px-3 py-2 rounded-lg bg-gray-100 text-gray-700 font-semibold flex items-center justify-center gap-2"><Ban className="w-4 h-4"/>No refund</button></div>
 </div>{error[d.id]&&<div className="mt-3 p-3 rounded-lg bg-red-50 text-red-700 text-sm font-medium">{error[d.id]}</div>}<div className="mt-3 flex justify-between items-center"><p className="text-xs text-gray-400">Refunds are executed through Stripe and actions are written to the Admin Audit Log.</p><button disabled={busy===d.id} onClick={()=>act(d,"close")} className="text-xs font-semibold text-gray-500 hover:text-gray-800">Close dispute</button></div></div>
 </div>}</div>})}</div>}</div></AdminLayout>
}
