import { useEffect,useState,useRef } from "react";
import { Search,RefreshCw,Package,Truck,ShieldCheck,RotateCcw,XCircle,ChevronRight,CreditCard } from "lucide-react";
import { AdminLayout } from "./AdminLayout";
import { useAdmin } from "@/context/AdminContext";

type Order=Record<string,any>; const statuses=["","pending","confirmed","preparing","shipped","out_for_delivery","delivered","cancelled","refunded"];
const money=(v:any,c="GBP")=>new Intl.NumberFormat(undefined,{style:"currency",currency:c||"GBP"}).format(Number(v||0));
export function AdminOrdersPage(){const {authFetch}=useAdmin();const [orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(false),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [listError,setListError]=useState("");
 const [testOpen,setTestOpen]=useState(false),[testBuyer,setTestBuyer]=useState(""),[testSeller,setTestSeller]=useState(""),[testBusy,setTestBusy]=useState(false),[testError,setTestError]=useState("");
 const loadVersion=useRef(0), detailVersion=useRef(0);
 async function readResponse(r:Response,message:string){
   let d:any;try{d=await r.json()}catch{throw new Error(message)}
   if(!r.ok)throw new Error(typeof d?.error==="string"?d.error:message);
   return d;
 }
 async function load(){const version=++loadVersion.current;setLoading(true);setListError("");try{
   const r=await authFetch(`/api/admin/orders?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`);
   const d=await readResponse(r,"Could not load orders. Please retry.");
   const rows=Array.isArray(d)?d:d?.orders;
   if(!Array.isArray(rows)||!rows.every(o=>o&&typeof o==="object"&&!Array.isArray(o)&&typeof o.id==="string"))throw new Error("Invalid orders response. Please retry.");
   if(version===loadVersion.current)setOrders(rows);
 }catch(e:any){if(version===loadVersion.current){setListError(e.message||"Could not load orders. Please retry.");setOrders([])}}finally{if(version===loadVersion.current)setLoading(false)}}
 async function open(id:string){const version=++detailVersion.current;setSelected(id);setDetail(null);setError("");try{
   const r=await authFetch(`/api/admin/orders/${id}/command`);const d=await readResponse(r,"Could not load order. Please retry.");
   if(!d?.order?.id||!d.payment||!Array.isArray(d.timeline))throw new Error("Invalid order details. Please retry.");
   if(version===detailVersion.current)setDetail(d);
 }catch(e:any){if(version===detailVersion.current)setError(e.message||"Could not load order. Please retry.")}}
 useEffect(()=>{const t=setTimeout(load,300);return()=>{clearTimeout(t);loadVersion.current++}},[q,status]);
 async function action(path:string,method:string,body:object,message:string){
   if(!detail||busy)return;const id=detail.order.id;setBusy(true);setError("");
   try{const r=await authFetch(`/api/admin/orders/${id}${path}`,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
     const d=await readResponse(r,message);await load();await open(id);if(d?.warning)setError(d.warning);
   }catch(e:any){setError(e.message||message)}finally{setBusy(false)}
 }
 async function refreshTracking(){if(!detail||busy)return;const id=detail.order.id;setBusy(true);setError("");try{const r=await authFetch(`/api/admin/orders/${id}/tracking/refresh`,{method:"POST"});await readResponse(r,"Shippo tracking refresh failed.");await load();await open(id);}catch(e:any){setError(e.message||"Shippo tracking refresh failed.")}finally{setBusy(false)}}
 async function save(){if(!detail)return;const o=detail.order;await action("","PATCH",{status:o.status,trackingNumber:o.tracking_number,carrier:o.carrier,estimatedDelivery:o.estimated_delivery},"Save failed. Please retry.")}
 async function cancel(){if(!detail||busy||!confirm("Cancel this order? This does not automatically refund the payment."))return;await action("/cancel","POST",{},"Cancel failed. Please retry.")}
 async function releasePayout(){if(!detail||busy||!confirm("Transfer this order's net proceeds to the seller's connected Stripe account, or retry a pending reversal?"))return;await action("/release-payout","POST",{},"Payout release failed. Please check the order before retrying.")}
 async function refund(){if(!detail||busy)return;const suggested=Math.max(0,Number(detail.order.buyer_total??(Number(detail.order.price||0)+Number(detail.order.buyer_protection_fee||0)+Number(detail.order.delivery_fee||0)))-Number(detail.order.refunded_total||0)).toFixed(2);const raw=prompt(`Refund amount (${detail.payment.currency}). Default is this order’s remaining item, protection and delivery amount.`,suggested);if(raw===null)return;const amount=Number(raw);if(!Number.isFinite(amount)||amount<=0){setError("Enter a valid positive refund amount.");return;}if(!confirm(`Issue a REAL Stripe refund of ${money(amount,detail.payment.currency)}?`))return;await action("/refund","POST",{amount},"Refund failed. Check the order and Stripe before retrying.")}
 async function createTestSale(){if(!testBuyer.trim()||!testSeller.trim()){setTestError("Enter an existing buyer and seller email.");return;}setTestBusy(true);setTestError("");try{const r=await authFetch("/api/admin/orders/test-sale",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({buyerEmail:testBuyer.trim(),sellerEmail:testSeller.trim(),itemTitle:"Shippo Tracking Test Item"})});const d=await readResponse(r,"Could not create test sale.");setTestOpen(false);setTestBuyer("");setTestSeller("");await load();await open(d.id);}catch(e:any){setTestError(e.message||"Could not create test sale.")}finally{setTestBusy(false)}}
 const active=orders.filter(o=>!["delivered","cancelled","refunded"].includes(o.status)).length, paid=orders.filter(o=>o.payment_status==="paid").length, disputes=orders.filter(o=>o.dispute_status&&!["closed","resolved_no_action","resolved_refund"].includes(o.dispute_status)).length, deliveryExceptions=orders.filter(o=>["RETURNED","FAILURE"].includes(String(o.tracking_status||"").toUpperCase())).length;
 return <AdminLayout><div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-gray-900">Order Command Centre</h1><p className="text-sm text-gray-500">Payments, fulfilment, tracking, Buyer Protection, disputes, cancellations and refunds.</p></div><div className="flex gap-2"><button onClick={()=>{setTestOpen(true);setTestError("")}} className="rounded-xl bg-blue-600 text-white px-4 py-2 text-sm font-bold">Create Test Sale</button><button onClick={load} className="flex gap-2 items-center text-sm font-bold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></div></div>
 {listError&&<div role="alert" className="bg-red-50 text-red-700 p-3 rounded-xl text-sm">{listError}</div>}
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["Orders",orders.length,Package],["Active fulfilment",active,Truck],["Paid",paid,CreditCard],["Open disputes",disputes,ShieldCheck],["Delivery problems",deliveryExceptions,Truck]].map(([a,b,I]:any)=><div className="bg-white border rounded-2xl p-4" key={a}><I className="w-5 h-5 text-orange-500"/><p className="text-2xl font-black mt-2">{b}</p><p className="text-xs text-gray-500">{a}</p></div>)}</div>
 <div className="bg-white border rounded-2xl p-3 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Order ID, buyer, seller, product or tracking…" className="w-full border rounded-xl pl-9 pr-3 py-2 text-sm"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-xl px-3 text-sm">{statuses.map(s=><option value={s} key={s}>{s?s.replaceAll('_',' '):'All statuses'}</option>)}</select></div>
 <div className="bg-white border rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr>{["Order","Item","Buyer / Seller","Payment","Dispatch","Protection","Total",""] .map(x=><th className="text-left px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className={`border-t hover:bg-gray-50 ${["RETURNED","FAILURE"].includes(String(o.tracking_status||"").toUpperCase())?"bg-red-50":""}`}><td className="px-4 py-3"><b>{o.id}</b><div className="text-xs text-gray-400">{new Date(o.created_at).toLocaleDateString()}</div></td><td className="px-4 py-3 max-w-[260px] truncate">{o.item_title}</td><td className="px-4 py-3 text-xs"><div>{o.buyer_email}</div><div className="text-gray-400">{o.seller_email||'—'}</div></td><td className="px-4 py-3"><span className={`px-2 py-1 rounded-full text-xs font-bold ${o.payment_status==='paid'?'bg-emerald-50 text-emerald-700':'bg-gray-100'}`}>{o.payment_status}</span></td><td className="px-4 py-3"><b className="text-xs">{String(o.status).replaceAll('_',' ')}</b>{["RETURNED","FAILURE"].includes(String(o.tracking_status||"").toUpperCase())&&<div className="mt-1 inline-block rounded-full bg-red-100 text-red-700 px-2 py-0.5 text-[11px] font-black">DELIVERY PROBLEM · {o.tracking_status}</div>}<div className="text-xs text-gray-400">{o.carrier||''} {o.tracking_number||''}</div></td><td className="px-4 py-3 text-xs">{o.dispute_status?`Dispute: ${o.dispute_status}`:o.return_status?`Return: ${o.return_status}`:'Protected'}</td><td className="px-4 py-3 font-black">{money(Number(o.buyer_total??(Number(o.price)+Number(o.buyer_protection_fee||0)+Number(o.delivery_fee||0))),o.payment_currency)}</td><td><button onClick={()=>open(o.id)} className="p-2"><ChevronRight className="w-4 h-4"/></button></td></tr>)}{!orders.length&&!loading&&!listError&&<tr><td colSpan={8} className="p-10 text-center text-gray-400">No orders found</td></tr>}</tbody></table></div></div></div>
 {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex justify-end" onClick={()=>setSelected(null)}><div className="w-full max-w-2xl bg-white h-full overflow-y-auto p-6" onClick={e=>e.stopPropagation()}>{!detail?<div>{error?<p role="alert" className="bg-red-50 text-red-700 p-3 rounded-xl">{error}</p>:<p>Loading…</p>}<button className="mt-3 underline" onClick={()=>setSelected(null)}>Close</button>{error&&<button className="ml-3 underline" onClick={()=>open(selected)}>Retry</button>}</div>:<><div className="flex justify-between"><div><h2 className="text-xl font-black">{detail.order.id}</h2><p className="text-sm text-gray-500">{detail.order.item_title}</p></div><button onClick={()=>setSelected(null)}><XCircle/></button></div>{error&&<div role="alert" className="mt-4 bg-red-50 text-red-700 p-3 rounded-xl text-sm">{error}</div>}
 <div className="grid grid-cols-2 gap-3 mt-5"><div className="border rounded-xl p-3"><p className="text-xs text-gray-400">Payment</p><b>{detail.payment.status}</b><p>{money(detail.payment.total,detail.payment.currency)} paid · {money(detail.payment.refunded,detail.payment.currency)} refunded</p></div><div className="border rounded-xl p-3"><p className="text-xs text-gray-400">Buyer Protection</p><b>{money(detail.order.buyer_protection_fee,detail.payment.currency)}</b><p className="text-xs text-gray-500">Selling fee: {money(detail.order.seller_fee,"GBP")} · protection and support included</p><p className="text-xs font-bold">Seller net: {money(detail.order.seller_net??(Number(detail.order.price)-Number(detail.order.seller_fee||0)),"GBP")}</p><p className="text-xs">Payout: {detail.order.payout_status||"awaiting release"}</p></div></div>
 {["RETURNED","FAILURE"].includes(String(detail.order.tracking_status||"").toUpperCase())&&<div role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800"><b>Delivery exception requires attention</b><p className="text-sm mt-1">{detail.order.tracking_last_event||"Shippo reported a returned or failed delivery. Review tracking and contact the buyer/seller as needed."}</p></div>}<div className="mt-5 border rounded-2xl p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">Shippo tracking</h3><p className="text-xs text-gray-500 mt-1">{detail.order.carrier&&detail.order.tracking_number?`${detail.order.carrier} · ${detail.order.tracking_number}`:"No tracking number on this order"}</p></div><button disabled={busy||!detail.order.carrier||!detail.order.tracking_number} onClick={refreshTracking} className="bg-blue-600 text-white rounded-xl px-4 py-2 text-sm font-bold disabled:opacity-40">{busy?"Checking…":"Refresh Shippo Tracking"}</button></div><div className="grid sm:grid-cols-2 gap-3 mt-4"><div className="bg-gray-50 rounded-xl p-3"><p className="text-xs text-gray-500">Carrier status</p><b>{detail.order.tracking_status||"Not received from Shippo yet"}</b></div><div className="bg-gray-50 rounded-xl p-3"><p className="text-xs text-gray-500">ETA</p><b>{detail.order.tracking_eta?new Date(detail.order.tracking_eta).toLocaleString():"—"}</b></div><div className="bg-gray-50 rounded-xl p-3 sm:col-span-2"><p className="text-xs text-gray-500">Latest event</p><b>{detail.order.tracking_last_event||"No Shippo event stored"}</b><p className="text-[11px] text-gray-400 mt-1">{detail.order.tracking_updated_at?`Last checked ${new Date(detail.order.tracking_updated_at).toLocaleString()}`:"Never refreshed successfully"} · {Array.isArray(detail.order.tracking_history)?detail.order.tracking_history.length:0} history events</p></div></div></div>
 <div className="mt-5 border rounded-2xl p-4"><h3 className="font-black mb-3">Fulfilment controls</h3><div className="grid grid-cols-2 gap-3"><select value={detail.order.status} onChange={e=>setDetail({...detail,order:{...detail.order,status:e.target.value}})} className="border rounded-xl p-2">{statuses.filter(Boolean).map(s=><option key={s}>{s}</option>)}</select><input placeholder="Carrier" value={detail.order.carrier||''} onChange={e=>setDetail({...detail,order:{...detail.order,carrier:e.target.value}})} className="border rounded-xl p-2"/><input placeholder="Tracking number" value={detail.order.tracking_number||''} onChange={e=>setDetail({...detail,order:{...detail.order,tracking_number:e.target.value}})} className="border rounded-xl p-2"/><input placeholder="Estimated delivery" value={detail.order.estimated_delivery||''} onChange={e=>setDetail({...detail,order:{...detail.order,estimated_delivery:e.target.value}})} className="border rounded-xl p-2"/></div><button disabled={busy} onClick={save} className="mt-3 bg-gray-900 text-white rounded-xl px-4 py-2 font-bold">Save order</button></div>
 <div className="mt-5 flex flex-wrap gap-2"><button disabled={busy || (detail.order.status!=="delivered" && !["reversal_pending","refund_pending"].includes(detail.order.payout_status)) || detail.order.payout_status==="paid"} onClick={releasePayout} className="bg-emerald-600 text-white rounded-xl px-4 py-2 font-bold">{["reversal_pending","refund_pending"].includes(detail.order.payout_status) ? "Retry payout reconciliation" : "Release seller payout"}</button><button disabled={busy||detail.order.status==='cancelled'} onClick={cancel} className="border border-red-200 text-red-700 rounded-xl px-4 py-2 font-bold">Cancel order</button><button disabled={busy||detail.payment.status!=='paid'||detail.payment.refundable<=0} onClick={refund} className="bg-red-600 text-white rounded-xl px-4 py-2 font-bold flex items-center gap-2"><RotateCcw className="w-4 h-4"/>Issue Stripe refund</button></div>
 <div className="mt-6"><h3 className="font-black mb-3">Order timeline</h3><div className="space-y-3">{detail.timeline.map((x:any,i:number)=><div key={i} className="border-l-2 border-orange-300 pl-4"><b className="text-sm">{x.title}</b><p className="text-xs text-gray-500">{x.detail||''}</p><p className="text-[11px] text-gray-400">{new Date(x.at).toLocaleString()}</p></div>)}</div></div></>}</div></div>}{testOpen&&<div className="fixed inset-0 z-[70] bg-black/50 flex items-center justify-center p-4" onClick={()=>setTestOpen(false)}><div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-black">Create Test Sale</h2><p className="text-sm text-gray-500 mt-1">Creates a £0 Bazunk order for testing Shippo. No Stripe payment and no seller payout.</p><label className="block text-sm font-bold mt-5">Buyer account email</label><input value={testBuyer} onChange={e=>setTestBuyer(e.target.value)} className="mt-1 w-full border rounded-xl p-2.5" placeholder="buyer@example.com"/><label className="block text-sm font-bold mt-3">Seller account email</label><input value={testSeller} onChange={e=>setTestSeller(e.target.value)} className="mt-1 w-full border rounded-xl p-2.5" placeholder="seller@example.com"/>{testError&&<p className="mt-3 text-sm text-red-600">{testError}</p>}<div className="flex justify-end gap-2 mt-5"><button onClick={()=>setTestOpen(false)} className="border rounded-xl px-4 py-2 font-bold">Cancel</button><button disabled={testBusy} onClick={createTestSale} className="bg-blue-600 text-white rounded-xl px-4 py-2 font-bold disabled:opacity-50">{testBusy?"Creating…":"Create test sale"}</button></div></div></div>}</AdminLayout>}
