import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { Activity, ChevronDown, ChevronUp, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { AdminLayout } from "./AdminLayout";
import { useAdmin } from "@/context/AdminContext";

type Entry = { id:string; actor:string; category:string; action:string; target_type?:string; target_id?:string; summary:string; before_data?:any; after_data?:any; metadata?:any; ip_address?:string; user_agent?:string; created_at:string };
const CATS=["all","users","credits","fees","settings","orders","listings","importers","reviews","live"];
function JsonBox({label,value}:{label:string,value:any}) { if(value==null) return null; return <div><p className="text-[10px] font-bold uppercase tracking-wide text-gray-400 mb-1">{label}</p><pre className="text-[11px] bg-gray-950 text-gray-200 rounded-xl p-3 overflow-auto max-h-52">{JSON.stringify(value,null,2)}</pre></div> }
export function AdminAuditLogPage(){
 const {isAdmin,authFetch}=useAdmin(); const [,setLocation]=useLocation(); const [entries,setEntries]=useState<Entry[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [category,setCategory]=useState("all"); const [open,setOpen]=useState<string|null>(null);
 useEffect(()=>{if(!isAdmin)setLocation("/admin")},[isAdmin]);
 async function load(){setLoading(true);try{const p=new URLSearchParams({limit:"150"});if(search.trim())p.set("search",search.trim());if(category!=="all")p.set("category",category);const r=await authFetch(`/api/admin/audit-log?${p}`);if(r.ok){const d=await r.json();setEntries(d.entries??[]);setTotal(d.total??0)}}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,category]);
 const grouped=useMemo(()=>entries, [entries]);
 return <AdminLayout><div className="max-w-[1500px] mx-auto">
  <div className="flex items-start justify-between gap-4 mb-6"><div><div className="flex items-center gap-2"><ShieldCheck className="w-6 h-6 text-[#F26B21]"/><h1 className="text-2xl font-black text-gray-900">Admin Audit Log</h1></div><p className="text-sm text-gray-500 mt-1">Immutable record of administrative changes · {total.toLocaleString()} events</p></div><button onClick={load} className="flex items-center gap-2 px-3 py-2 rounded-xl border bg-white text-sm font-semibold text-gray-600"><RefreshCw className={`w-4 h-4 ${loading?"animate-spin":""}`}/>Refresh</button></div>
  <div className="bg-white border border-gray-100 shadow-sm rounded-2xl p-3 mb-4 flex flex-wrap gap-2"><div className="relative flex-1 min-w-64"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search action, user, order, listing or ID…" className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-gray-200 text-sm outline-none focus:ring-2 focus:ring-orange-100"/></div><select value={category} onChange={e=>setCategory(e.target.value)} className="px-3 py-2.5 rounded-xl border border-gray-200 text-sm bg-white">{CATS.map(c=><option key={c} value={c}>{c==="all"?"All categories":c[0].toUpperCase()+c.slice(1)}</option>)}</select></div>
  <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
   {loading&&entries.length===0?<div className="py-20 text-center text-gray-400">Loading audit history…</div>:grouped.length===0?<div className="py-20 text-center"><Activity className="w-10 h-10 mx-auto text-gray-200 mb-3"/><p className="text-gray-500 font-semibold">No matching audit events</p></div>:grouped.map(e=>{const expanded=open===e.id;return <div key={e.id} className="border-b border-gray-100 last:border-0"><button onClick={()=>setOpen(expanded?null:e.id)} className="w-full text-left px-5 py-4 hover:bg-gray-50 flex gap-4 items-start"><div className="mt-1 w-2 h-2 rounded-full bg-[#F26B21] shrink-0"/><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-bold text-gray-900">{e.summary}</span><span className="px-2 py-0.5 rounded-full bg-gray-100 text-[10px] font-bold uppercase text-gray-500">{e.category}</span></div><div className="text-xs text-gray-400 mt-1">{e.actor} · {new Date(e.created_at).toLocaleString()} {e.target_id?`· ${e.target_type??"target"}: ${e.target_id}`:""}</div></div>{expanded?<ChevronUp className="w-4 h-4 text-gray-400"/>:<ChevronDown className="w-4 h-4 text-gray-400"/>}</button>{expanded&&<div className="px-10 pb-5 grid lg:grid-cols-2 gap-3"><JsonBox label="Before" value={e.before_data}/><JsonBox label="After" value={e.after_data}/><JsonBox label="Metadata" value={e.metadata}/><div className="text-xs text-gray-500 bg-gray-50 rounded-xl p-3"><b>Debug details</b><br/>Action: {e.action}<br/>Event ID: {e.id}<br/>{e.ip_address&&<>IP: {e.ip_address}<br/></>}{e.user_agent&&<span className="break-all">User agent: {e.user_agent}</span>}</div></div>}</div>})}
  </div><p className="text-xs text-gray-400 mt-3">Audit entries are read-only. The Admin UI intentionally provides no delete control.</p>
 </div></AdminLayout>
}
