import { useEffect,useState } from "react";
import { Search,RefreshCw,Package,Truck,ShieldCheck,RotateCcw,XCircle,ChevronRight,CreditCard } from "lucide-react";
import { AdminLayout } from "./AdminLayout";
import { useAdmin } from "@/context/AdminContext";

type Order=Record<string,any>; const statuses=["","pending","confirmed","preparing","shipped","out_for_delivery","delivered","cancelled","refunded"];
const money=(v:any,c="GBP")=>new Intl.NumberFormat(undefined,{style:"currency",currency:c||"GBP"}).format(Number(v||0));
export function AdminOrdersPage(){const {authFetch}=useAdmin();const [orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(false),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await authFetch(`/api/admin/orders?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`);const d=await r.json();setOrders(d.orders||d||[]);}finally{setLoading(false)}}
 async function open(id:string){setSelected(id);setDetail(null);setError("");const r=await authFetch(`/api/admin/orders/${id}/command`);const d=await r.json();if(r.ok)setDetail(d);else setError(d.error||"Could not load order");}
 useEffect(()=>{load()},[status]); useEffect(()=>{const t=setTimeout(load,300);return()=>clearTimeout(t)},[q]);
 async function save(){if(!detail)return;setBusy(true);setError("");const o=detail.order;const r=await authFetch(`/api/admin/orders/${o.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:o.status,trackingNumber:o.tracking_number,carrier:o.carrier,estimatedDelivery:o.estimated_delivery})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Save failed");return;}await load();await open(o.id)}
 async function cancel(){if(!detail||!confirm("Cancel this order? This does not automatically refund the payment."))return;setBusy(true);const r=await authFetch(`/api/admin/orders/${detail.order.id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Cancel failed");return;}await load();await open(detail.order.id)}
 async function refund(){if(!detail)return;const suggested=(Number(detail.order.price||0)+Number(detail.order.buyer_protection_fee||0)).toFixed(2);const raw=prompt(`Refund amount (${detail.payment.currency}). Default is item + Buyer Protection.`,suggested);if(raw===null)return;const amount=Number(raw);if(!amount||amount<=0)return; if(!confirm(`Issue a REAL Stripe refund of ${money(amount,detail.payment.currency)}?`))return;setBusy(true);const r=await authFetch(`/api/admin/orders/${detail.order.id}/refund`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Refund failed");return;}await load();await open(detail.order.id)}
 const active=orders.filter(o=>!["delivered","cancelled","refunded"].includes(o.status)).length, paid=orders.filter(o=>o.payment_status==="paid").length, disputes=orders.filter(o=>o.dispute_status&&!["closed","resolved_no_action","resolved_refund"].includes(o.dispute_status)).length;
 return <AdminLayout><div className="space-y-5"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-gray-900">Order Command Centre</h1><p className="text-sm text-gray-500">Payments, fulfilment, tracking, Buyer Protection, disputes, cancellations and refunds.</p></div><button onClick={load} className="flex gap-2 items-center text-sm font-bold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["Orders",orders.length,Package],["Active fulfilment",active,Truck],["Paid",paid,CreditCard],["Open disputes",disputes,ShieldCheck]].map(([a,b,I]:any)=><div className="bg-white border rounded-2xl p-4" key={a}><I className="w-5 h-5 text-orange-500"/><p className="text-2xl font-black mt-2">{b}</p><p className="text-xs text-gray-500">{a}</p></div>)}</div>
 <div className="bg-white border rounded-2xl p-3 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-gray-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Order ID, buyer, seller, product or tracking…" className="w-full border rounded-xl pl-9 pr-3 py-2 text-sm"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-xl px-3 text-sm">{statuses.map(s=><option value={s} key={s}>{s?s.replaceAll('_',' '):'All statuses'}</option>)}</select></div>
 <div className="bg-white border rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr>{["Order","Item","Buyer / Seller","Payment","Dispatch","Protection","Total",""] .map(x=><th className="text-left px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-t hover:bg-gray-50"><td className="px-4 py-3"><b>{o.id}</b><div className="text-xs text-gray-400">{new Date(o.created_at).toLocaleDateString()}</div></td><td className="px-4 py-3 max-w-[260px] truncate">{o.item_title}</td><td className="px-4 py-3 text-xs"><div>{o.buyer_email}</div><div className="text-gray-400">{o.seller_email||'—'}</div></td><td className="px-4 py-3"><span className={`px-2 py-1 rounded-full text-xs font-bold ${o.payment_status==='paid'?'bg-emerald-50 text-emerald-700':'bg-gray-100'}`}>{o.payment_status}</span></td><td className="px-4 py-3"><b className="text-xs">{String(o.status).replaceAll('_',' ')}</b><div className="text-xs text-gray-400">{o.carrier||''} {o.tracking_number||''}</div></td><td className="px-4 py-3 text-xs">{o.dispute_status?`Dispute: ${o.dispute_status}`:o.return_status?`Return: ${o.return_status}`:'Protected'}</td><td className="px-4 py-3 font-black">{money(Number(o.price)+Number(o.buyer_protection_fee||0),o.payment_currency)}</td><td><button onClick={()=>open(o.id)} className="p-2"><ChevronRight className="w-4 h-4"/></button></td></tr>)}{!orders.length&&!loading&&<tr><td colSpan={8} className="p-10 text-center text-gray-400">No orders found</td></tr>}</tbody></table></div></div></div>
 {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex justify-end" onClick={()=>setSelected(null)}><div className="w-full max-w-2xl bg-white h-full overflow-y-auto p-6" onClick={e=>e.stopPropagation()}>{!detail?<p>Loading…</p>:<><div className="flex justify-between"><div><h2 className="text-xl font-black">{detail.order.id}</h2><p className="text-sm text-gray-500">{detail.order.item_title}</p></div><button onClick={()=>setSelected(null)}><XCircle/></button></div>{error&&<div className="mt-4 bg-red-50 text-red-700 p-3 rounded-xl text-sm">{error}</div>}
 <div className="grid grid-cols-2 gap-3 mt-5"><div className="border rounded-xl p-3"><p className="text-xs text-gray-400">Payment</p><b>{detail.payment.status}</b><p>{money(detail.payment.total,detail.payment.currency)} paid · {money(detail.payment.refunded,detail.payment.currency)} refunded</p></div><div className="border rounded-xl p-3"><p className="text-xs text-gray-400">Buyer Protection</p><b>{money(detail.order.buyer_protection_fee,detail.payment.currency)}</b><p className="text-xs text-gray-500">Business fee: {money(detail.order.seller_fee,detail.payment.currency)}</p></div></div>
 <div className="mt-5 border rounded-2xl p-4"><h3 className="font-black mb-3">Fulfilment controls</h3><div className="grid grid-cols-2 gap-3"><select value={detail.order.status} onChange={e=>setDetail({...detail,order:{...detail.order,status:e.target.value}})} className="border rounded-xl p-2">{statuses.filter(Boolean).map(s=><option key={s}>{s}</option>)}</select><input placeholder="Carrier" value={detail.order.carrier||''} onChange={e=>setDetail({...detail,order:{...detail.order,carrier:e.target.value}})} className="border rounded-xl p-2"/><input placeholder="Tracking number" value={detail.order.tracking_number||''} onChange={e=>setDetail({...detail,order:{...detail.order,tracking_number:e.target.value}})} className="border rounded-xl p-2"/><input placeholder="Estimated delivery" value={detail.order.estimated_delivery||''} onChange={e=>setDetail({...detail,order:{...detail.order,estimated_delivery:e.target.value}})} className="border rounded-xl p-2"/></div><button disabled={busy} onClick={save} className="mt-3 bg-gray-900 text-white rounded-xl px-4 py-2 font-bold">Save order</button></div>
 <div className="mt-5 flex gap-2"><button disabled={busy||detail.order.status==='cancelled'} onClick={cancel} className="border border-red-200 text-red-700 rounded-xl px-4 py-2 font-bold">Cancel order</button><button disabled={busy||detail.payment.status!=='paid'||detail.payment.refundable<=0} onClick={refund} className="bg-red-600 text-white rounded-xl px-4 py-2 font-bold flex items-center gap-2"><RotateCcw className="w-4 h-4"/>Issue Stripe refund</button></div>
 <div className="mt-6"><h3 className="font-black mb-3">Order timeline</h3><div className="space-y-3">{detail.timeline.map((x:any,i:number)=><div key={i} className="border-l-2 border-orange-300 pl-4"><b className="text-sm">{x.title}</b><p className="text-xs text-gray-500">{x.detail||''}</p><p className="text-[11px] text-gray-400">{new Date(x.at).toLocaleString()}</p></div>)}</div></div></>}</div></div>}</AdminLayout>}
