import { ShieldCheck, PackageX, BadgeAlert, Headphones, ArrowLeft, Calculator, Store } from "lucide-react";
import { Link } from "wouter";

export default function BuyerProtectionPage() {
  return <div className="min-h-screen bg-[#0f172a] text-white">
    <div className="max-w-6xl mx-auto px-4 py-6"><Link href="/" className="inline-flex items-center gap-2 text-white/70 hover:text-white"><ArrowLeft className="w-4 h-4"/> Back to home</Link></div>
    <section className="max-w-6xl mx-auto px-4 pb-12 grid lg:grid-cols-2 gap-8 items-center"><div><div className="inline-flex items-center gap-2 text-emerald-400 font-black text-sm"><ShieldCheck className="w-5 h-5"/> BAZUNK BUYER PROTECTION</div><h1 className="text-4xl md:text-6xl font-black mt-4">Buy with confidence.</h1><p className="text-white/65 text-lg mt-4 leading-relaxed">When you pay through Bazunk, eligible purchases are protected if the item doesn't arrive, arrives damaged, or is significantly not as described.</p><div className="mt-6 rounded-2xl bg-white/5 border border-white/10 p-5"><p className="font-black">Buyer Protection fee</p><div className="grid grid-cols-3 gap-3 mt-3 text-center"><div><b>UK</b><br/><span className="text-emerald-400">6% + 70p</span></div><div><b>USA</b><br/><span className="text-emerald-400">6% + $1</span></div><div><b>EU</b><br/><span className="text-emerald-400">6% + €1</span></div></div><p className="text-xs text-white/45 mt-4">The fee is mandatory on protected marketplace checkout orders and is shown before payment.</p></div></div><img src="/assets/bazunk-buyer-protection.jpg" alt="Bazunk Trusted Buyer Protection" className="rounded-3xl border border-white/10 shadow-2xl w-full"/></section>
    <section className="bg-white text-gray-900 py-16"><div className="max-w-5xl mx-auto px-4"><h2 className="text-3xl font-black text-center">What it covers</h2><div className="grid md:grid-cols-3 gap-5 mt-8">{[[PackageX,"Doesn't arrive","Report an eligible order that never reaches you."],[BadgeAlert,"Damaged or not as described","Get help when an eligible item arrives damaged or is significantly different from the listing."],[Headphones,"Bazunk support","Open a dispute and provide evidence so our team can review the order."]].map(([Icon,t,d]:any)=><div key={t} className="rounded-2xl border border-gray-200 p-6"><Icon className="w-7 h-7 text-[#4A5CE8]"/><h3 className="font-black mt-4">{t}</h3><p className="text-sm text-gray-500 mt-2">{d}</p></div>)}</div>
    <div className="mt-10 grid md:grid-cols-2 gap-6"><div className="rounded-2xl bg-emerald-50 border border-emerald-100 p-6"><Calculator className="w-6 h-6 text-emerald-600"/><h3 className="font-black mt-3">Example: £50 item</h3><div className="mt-3 text-sm space-y-2"><div className="flex justify-between"><span>Item</span><b>£50.00</b></div><div className="flex justify-between"><span>Buyer Protection (6% + 70p)</span><b>£3.70</b></div><div className="flex justify-between border-t border-emerald-200 pt-2"><span>Before delivery</span><b>£53.70</b></div></div></div><div className="rounded-2xl bg-orange-50 border border-orange-100 p-6"><Store className="w-6 h-6 text-[#F26B21]"/><h3 className="font-black mt-3">Private sellers sell free</h3><p className="text-sm text-gray-600 mt-2">A private seller listing an item for £50 keeps the £50 item price. There is no Bazunk listing fee or private-seller commission. Registered businesses and sole traders may have separate business seller fees.</p></div></div>
    <div className="mt-10 rounded-2xl bg-gray-50 border border-gray-200 p-6"><h3 className="font-black">If something goes wrong</h3><p className="text-sm text-gray-600 mt-2">Open a dispute from your Dashboard as soon as you discover the problem. Keep photographs, tracking information and your messages with the seller. Bazunk will review the evidence and the order status. Protection is for eligible purchases completed through Bazunk checkout; direct/off-platform transactions and contact-only classifieds are not covered.</p></div>
    <div className="text-center mt-10"><Link href="/support" className="inline-flex px-6 py-3 rounded-xl bg-[#4A5CE8] text-white font-black">Buyer Protection help</Link></div></div></section>
  </div>;
}
