import { useEffect,useState } from "react";
const labels:Record<string,string>={offers:"Offers and counteroffers",auction_bids:"Auction bids and outbid alerts",listing_updates:"Listing sold or ended",flash_sales:"Flash sales and promotions",rewards:"Rewards, milestones and credits",marketing:"Newsletters and marketing"};
const API=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
export function EmailPreferencesPage(){
 const params=new URLSearchParams(window.location.search),token=params.get("token")||"";
 const [email,setEmail]=useState(""),[prefs,setPrefs]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{if(!token){setBusy(false);setMessage("This email preferences link is missing its secure token.");return;}
 fetch(API+"/api/email-preferences?token="+encodeURIComponent(token)).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Could not load preferences");setEmail(d.email);const p=d.preferences as Record<string,boolean>;if(params.get("unsubscribe")==="marketing"){p.marketing=false;await fetch(API+"/api/email-preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,preferences:{marketing:false}})});setMessage("You have been unsubscribed from marketing emails.");}setPrefs({...p});}).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));},[token]);
 async function save(){setBusy(true);setMessage("");try{const r=await fetch(API+"/api/email-preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,preferences:prefs})});if(!r.ok)throw Error("Could not save preferences");setMessage("Your email preferences have been saved.");}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <main className="mx-auto max-w-2xl px-5 py-14"><h1 className="text-3xl font-bold mb-3">Email notification preferences</h1><p className="text-gray-600 mb-6">Choose which optional Bazunk emails you receive. Essential order, payment, security and dispute messages will still be sent.</p>{email&&<p className="mb-5 text-sm">Preferences for <strong>{email}</strong></p>}{message&&<p role="status" className="mb-5 rounded-lg bg-gray-100 p-3">{message}</p>}{Object.keys(prefs).length>0&&<div className="space-y-4">{Object.entries(labels).map(([key,label])=><label key={key} className="flex items-center justify-between gap-4 border rounded-xl p-4"><span>{label}</span><input type="checkbox" className="h-5 w-5" checked={prefs[key]!==false} onChange={e=>setPrefs(p=>({...p,[key]:e.target.checked}))}/></label>)}<button disabled={busy} onClick={save} className="rounded-xl bg-orange-600 px-6 py-3 text-white font-semibold disabled:opacity-50">Save preferences</button></div>}</main>;
}
