import { logger } from "./logger.js";
// Deployment marker: redeploy the current eBay public importer after the previous Render deploy was cancelled.
export interface PublicEbayItem { itemId:string;url:string;title:string;price:number;currency:string;image:string|null;condition:string;description:string;shipping:number|null;shippingLabel:string|null;available:boolean;categoryPath:string[] }
const ITEM_ID_RE=/(?:\/itm\/(?:[^/?#]+\/)?|item=)(\d{9,15})/i;
export function ebayItemId(input:string):string|null{const s=input.trim();if(/^\d{9,15}$/.test(s))return s;try{const u=new URL(s);return u.pathname.match(ITEM_ID_RE)?.[1]??u.searchParams.get("item")?.match(/^\d{9,15}$/)?.[0]??null}catch{return s.match(ITEM_ID_RE)?.[1]??null}}
export function canonicalEbayUrl(input:string):string{const id=ebayItemId(input);if(!id)throw new Error("Not a valid eBay item URL or item number.");let host="www.ebay.co.uk";try{if(new URL(input).hostname.toLowerCase().endsWith("ebay.com"))host="www.ebay.com"}catch{}return `https://${host}/itm/${id}`}
function decode(s:string):string{return s.replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#x2F;/gi,"/")}
function meta(html:string,key:string):string|null{for(const tag of html.match(/<meta\s+[^>]*>/gi)??[]){const k=tag.match(/(?:property|name)=["']([^"']+)["']/i)?.[1];if(k?.toLowerCase()!==key.toLowerCase())continue;const v=tag.match(/content=["']([^"']+)["']/i)?.[1];if(v)return decode(v.trim())}return null}
function jsonLd(html:string):any[]{const out:any[]=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;for(const m of html.matchAll(re)){try{const x=JSON.parse(decode(m[1]));if(Array.isArray(x))out.push(...x);else if(x?.["@graph"])out.push(...x["@graph"]);else out.push(x)}catch{}}return out}
function num(v:unknown):number|null{const n=parseFloat(String(v??"").replace(/[^0-9.,-]/g,"").replace(/,/g,""));return Number.isFinite(n)?n:null}
let ebayTokenCache:{token:string;expiresAt:number}|null=null;
async function ebayAppToken():Promise<string|null>{
 const clientId=process.env.EBAY_CLIENT_ID||process.env.EBAY_APP_ID||"";
 const clientSecret=process.env.EBAY_CLIENT_SECRET||process.env.EBAY_CERT_ID||"";
 if(!clientId||!clientSecret)return null;
 if(ebayTokenCache&&ebayTokenCache.expiresAt>Date.now()+60000)return ebayTokenCache.token;
 const basic=Buffer.from(`${clientId}:${clientSecret}`).toString("base64");
 const r=await fetch("https://api.ebay.com/identity/v1/oauth2/token",{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials&scope=https%3A%2F%2Fapi.ebay.com%2Foauth%2Fapi_scope"});
 if(!r.ok)throw new Error(`eBay OAuth returned HTTP ${r.status}`);
 const d:any=await r.json(); if(!d.access_token)throw new Error("eBay OAuth did not return an access token.");
 ebayTokenCache={token:String(d.access_token),expiresAt:Date.now()+Math.max(60,Number(d.expires_in||7200)-60)*1000}; return ebayTokenCache.token;
}
async function fetchOfficialEbayItem(input:string):Promise<PublicEbayItem|null>{
 const token=await ebayAppToken(); if(!token)return null;
 const itemId=ebayItemId(input); if(!itemId)return null;
 const url=canonicalEbayUrl(input),marketplace=url.includes(".co.uk")?"EBAY_GB":"EBAY_US";
 const endpoint=`https://api.ebay.com/buy/browse/v1/item/get_item_by_legacy_id?legacy_item_id=${encodeURIComponent(itemId)}&fieldgroups=PRODUCT`;
 const r=await fetch(endpoint,{headers:{Authorization:`Bearer ${token}`,"X-EBAY-C-MARKETPLACE-ID":marketplace,"Accept-Language":marketplace==="EBAY_GB"?"en-GB":"en-US"}});
 if(!r.ok){if(r.status===404)return null;throw new Error(`eBay Browse API returned HTTP ${r.status}`)}
 const d:any=await r.json(),price=num(d.price?.value);
 if(!d.title||price==null||price<=0)throw new Error("eBay Browse API returned incomplete listing data.");
 const shippingOpt=Array.isArray(d.shippingOptions)?d.shippingOptions[0]:null,ship=num(shippingOpt?.shippingCost?.value);
 const imageRaw=d.image?.imageUrl??d.product?.image?.imageUrl??null;
 return {itemId,url,title:String(d.title).trim(),price,currency:String(d.price?.currency|| (marketplace==="EBAY_GB"?"GBP":"USD")).toUpperCase(),image:typeof imageRaw==="string"?imageRaw.replace(/^http:/,"https:"):null,condition:String(d.condition||"used"),description:String(d.shortDescription||d.description||d.title).replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,5000),shipping:ship,shippingLabel:ship===0?"Free shipping":ship!=null?`${d.price?.currency||""} ${ship.toFixed(2)}`:null,available:!/OUT_OF_STOCK|SOLD_OUT/i.test(String(d.estimatedAvailabilities?.[0]?.estimatedAvailabilityStatus||"")),categoryPath:String(d.categoryPath||"").split("|").map((x:string)=>x.trim()).filter(Boolean)};
}
async function fetchHtml(url:string):Promise<string>{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(url,{signal:ctrl.signal,redirect:"follow",headers:{"user-agent":"Mozilla/5.0 (compatible; Mozilla/5.0 Windows NT 10.0 Win64 x64 AppleWebKit/537.36 Chrome/154 Safari/537.36)","accept":"text/html,application/xhtml+xml","accept-language":"en-GB,en;q=0.9"}});if(!r.ok)throw new Error(`eBay returned HTTP ${r.status}`);if(!(r.headers.get("content-type")??"").includes("text/html"))throw new Error("eBay did not return a listing page.");return await r.text()}finally{clearTimeout(timer)}}
export async function fetchPublicEbayItem(input:string):Promise<PublicEbayItem>{const official=await fetchOfficialEbayItem(input);if(official)return official;const url=canonicalEbayUrl(input),itemId=ebayItemId(url)!;const html=await fetchHtml(url);if(/captcha|robot check|verify you are human|security measure|pardon our interruption/i.test(html))throw new Error("eBay temporarily requires human verification. Try again later.");const nodes=jsonLd(html),product=nodes.find(x=>x?.["@type"]==="Product"||(Array.isArray(x?.["@type"])&&x["@type"].includes("Product")))??{},offer=Array.isArray(product.offers)?product.offers[0]:(product.offers??{});const title=String(product.name??meta(html,"og:title")??meta(html,"twitter:title")??"").replace(/\s*\|\s*eBay.*$/i,"").trim(),price=num(offer.price??offer.priceSpecification?.price??meta(html,"product:price:amount")??meta(html,"og:price:amount")??meta(html,"twitter:data1"));const currency=String(offer.priceCurrency??meta(html,"product:price:currency")??(url.includes(".co.uk")?"GBP":"USD")).toUpperCase(),imageRaw=Array.isArray(product.image)?product.image[0]:(product.image??meta(html,"og:image"));const image=typeof imageRaw==="string"&&/^https:\/\//i.test(imageRaw)?decode(imageRaw):null,condition=String(product.itemCondition??"").split("/").pop()?.replace(/Condition$/i,"").replace(/([a-z])([A-Z])/g,"$1 $2")||"used";const description=String(product.description??meta(html,"description")??title).replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim().slice(0,5000),availability=String(offer.availability??"");const available=!/OutOfStock|SoldOut|Discontinued/i.test(availability)&&!/This listing has ended|out of stock/i.test(html);let shipping:number|null=null,shippingLabel:string|null=null;const sd=Array.isArray(offer.shippingDetails)?offer.shippingDetails[0]:offer.shippingDetails;if(sd?.shippingRate){shipping=num(sd.shippingRate.value??sd.shippingRate);shippingLabel=shipping===0?"Free shipping":shipping!=null?`${currency} ${shipping.toFixed(2)}`:null}if(shipping==null){const sm=html.match(/(?:shipping|postage)[^£$€]{0,80}([£$€])\s*([0-9]+(?:\.[0-9]{1,2})?)/i);if(sm){shipping=num(sm[2]);shippingLabel=`${sm[1]}${sm[2]}`}}const crumbs=nodes.find(x=>x?.["@type"]==="BreadcrumbList")?.itemListElement,categoryPath=Array.isArray(crumbs)?crumbs.map((x:any)=>String(x?.item?.name??x?.name??"").trim()).filter(Boolean):[];if(!title||price==null||price<=0)throw new Error("eBay page loaded, but the public response did not contain a reliable title and price.");return{itemId,url,title,price,currency,image,condition,description,shipping,shippingLabel,available,categoryPath}}
export async function discoverPublicEbayUrls(pageUrl:string,limit=100):Promise<string[]>{let u:URL;try{u=new URL(pageUrl)}catch{throw new Error("Enter a valid eBay page URL.")}if(!/(^|\.)ebay\.(co\.uk|com)$/i.test(u.hostname))throw new Error("Only public eBay.co.uk or eBay.com pages are supported.");const html=await fetchHtml(u.toString()),ids=new Set<string>();for(const m of html.matchAll(/href=["']([^"']*\/itm\/[^"']+)["']/gi)){const id=ebayItemId(decode(m[1]));if(id)ids.add(id);if(ids.size>=Math.min(Math.max(limit,1),200))break}const host=u.hostname.endsWith("ebay.com")?"www.ebay.com":"www.ebay.co.uk";return[...ids].map(id=>`https://${host}/itm/${id}`)}
export async function fetchPublicEbayItems(inputs:string[],concurrency=2):Promise<{items:PublicEbayItem[];errors:{input:string;error:string}[]}>{const unique=[...new Set(inputs.map(x=>x.trim()).filter(Boolean))].slice(0,200),items:PublicEbayItem[]=[],errors:{input:string;error:string}[]=[];let next=0;async function worker(){while(next<unique.length){const input=unique[next++];try{items.push(await fetchPublicEbayItem(input))}catch(e){const error=e instanceof Error?e.message:String(e);errors.push({input,error});logger.warn({input,error},"Public eBay fetch failed")}await new Promise(r=>setTimeout(r,250))}}await Promise.all(Array.from({length:Math.min(concurrency,unique.length)},()=>worker()));return{items,errors}}
