import { useEffect, useState } from "react";
import { useAuth as useClerkAuth } from "@clerk/react";
import { Check, ChevronLeft, ChevronRight, CreditCard, MapPin, ShieldCheck, Store, User, Bell } from "lucide-react";

type Profile = {
  name:string; username:string; phone:string; addressLine1:string; addressLine2:string; city:string; postcode:string; country:string;
  sellerType:"private"|"sole_trader"|"business"; notificationPreferences:{orders:boolean;offers:boolean;messages:boolean;promotions:boolean};
};
const empty:Profile={name:"",username:"",phone:"",addressLine1:"",addressLine2:"",city:"",postcode:"",country:"United Kingdom",sellerType:"private",notificationPreferences:{orders:true,offers:true,messages:true,promotions:false}};
const steps=[User,MapPin,CreditCard,Store,Bell,Check];
const countries=["United Kingdom","Ireland","United States","Canada","Australia","France","Germany","Spain","Italy","Netherlands","Belgium","Portugal","Poland","Other"];

export function AccountSetupWizard({ fallbackName, onComplete }:{fallbackName:string;onComplete?:()=>void}){
  const {getToken}=useClerkAuth();
  const [loading,setLoading]=useState(true),[visible,setVisible]=useState(false),[saving,setSaving]=useState(false),[step,setStep]=useState(1);
  const [error,setError]=useState(""); const [p,setP]=useState<Profile>({...empty,name:fallbackName});
  async function api(method:string,body?:any){const token=await getToken();const r=await fetch("/api/listings/profile/me",{method,headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save your setup");return d;}
  useEffect(()=>{let live=true;(async()=>{try{const d=await api("GET");if(!live)return;if(d.onboarding_completed){setVisible(false);return;}setP({name:d.name||fallbackName||"",username:d.username||"",phone:d.phone||"",addressLine1:d.address_line1||"",addressLine2:d.address_line2||"",city:d.city||"",postcode:d.postcode||"",country:d.country||"United Kingdom",sellerType:d.seller_type||"private",notificationPreferences:{orders:d.notification_preferences?.orders!==false,offers:d.notification_preferences?.offers!==false,messages:d.notification_preferences?.messages!==false,promotions:d.notification_preferences?.promotions===true}});setStep(Math.max(1,Math.min(6,Number(d.onboarding_step)||1)));setVisible(true);}catch(e:any){console.error(e);setError("We couldn't load account setup. Refresh the page to try again.");setVisible(true);}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
  if(loading||!visible)return null;
  const update=(k:keyof Profile,v:any)=>setP(x=>({...x,[k]:v}));
  async function next(){setError("");if(step===1){if(!p.name.trim())return setError("Please enter your name.");if(!/^[A-Za-z0-9._-]{3,30}$/.test(p.username.trim().replace(/^@/,"")))return setError("Choose a username of 3–30 letters, numbers, dots, underscores or hyphens.");}if(step===2&&(!p.addressLine1.trim()||!p.city.trim()||!p.postcode.trim()||!p.country.trim()))return setError("Please complete the required address fields.");setSaving(true);try{const payload:any={onboardingStep:Math.min(6,step+1)};if(step===1)Object.assign(payload,{name:p.name,username:p.username,phone:p.phone});if(step===2)Object.assign(payload,{addressLine1:p.addressLine1,addressLine2:p.addressLine2,city:p.city,postcode:p.postcode,country:p.country});if(step===4)payload.sellerType=p.sellerType;if(step===5)payload.notificationPreferences=p.notificationPreferences;if(step===6)payload.onboardingCompleted=true;const d=await api("PATCH",payload);if(step===1&&d.username){setP(x=>({...x,username:d.username}));window.dispatchEvent(new CustomEvent("bazunk-profile-updated",{detail:{username:d.username}}));}if(step===6){setVisible(false);onComplete?.();}else setStep(x=>x+1);}catch(e:any){setError(e.message||"Unable to save");}finally{setSaving(false)}}
  const input="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm outline-none focus:border-[#4A5CE8] focus:ring-2 focus:ring-[#4A5CE8]/10";
  return <div className="fixed inset-0 z-[200] overflow-y-auto bg-slate-950/55 backdrop-blur-sm p-4 sm:p-8"><div className="mx-auto my-4 max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl">
    <div className="bg-gradient-to-r from-[#3448D8] to-[#5968EB] px-6 py-6 text-white"><div className="text-xs font-bold uppercase tracking-[.2em] text-white/70">Welcome to Bazunk</div><h1 className="mt-1 text-2xl font-black">Set up your account</h1><p className="mt-1 text-sm text-white/80">A few quick steps, then your Dashboard is ready.</p><div className="mt-5 flex gap-2">{steps.map((Icon,i)=><div key={i} className={`flex h-9 flex-1 items-center justify-center rounded-lg ${i+1<=step?"bg-white text-[#3B4FD8]":"bg-white/15 text-white/65"}`}><Icon className="h-4 w-4"/></div>)}</div></div>
    <div className="p-6 sm:p-8 min-h-[390px]">
      {step===1&&<><h2 className="text-xl font-black text-gray-900">Your profile</h2><p className="mt-1 text-sm text-gray-500">Your real name stays private. Your username is your public Bazunk identity.</p><div className="mt-6 space-y-4"><label className="block text-sm font-bold text-gray-700">Full name <span className="text-gray-400 font-normal">(private)</span><input className={`${input} mt-1.5`} value={p.name} onChange={e=>update("name",e.target.value)}/></label><label className="block text-sm font-bold text-gray-700">Public username<input className={`${input} mt-1.5`} value={p.username} onChange={e=>update("username",e.target.value.replace(/\s/g,""))} placeholder="yourusername"/><span className="mt-1 block text-xs font-normal text-gray-400">Shown as @{p.username||"yourusername"} on listings. Must be unique.</span></label><label className="block text-sm font-bold text-gray-700">Phone <span className="text-gray-400 font-normal">(optional, private)</span><input className={`${input} mt-1.5`} value={p.phone} onChange={e=>update("phone",e.target.value)} /></label></div></>}
      {step===2&&<><h2 className="text-xl font-black text-gray-900">Your address</h2><p className="mt-1 text-sm text-gray-500">Used for marketplace delivery and account services. It is never shown publicly on listings.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className={`${input} sm:col-span-2`} placeholder="Address line 1 *" value={p.addressLine1} onChange={e=>update("addressLine1",e.target.value)}/><input className={`${input} sm:col-span-2`} placeholder="Address line 2 (optional)" value={p.addressLine2} onChange={e=>update("addressLine2",e.target.value)}/><input className={input} placeholder="Town / city *" value={p.city} onChange={e=>update("city",e.target.value)}/><input className={input} placeholder="Postcode *" value={p.postcode} onChange={e=>update("postcode",e.target.value)}/><select className={`${input} sm:col-span-2`} value={p.country} onChange={e=>update("country",e.target.value)}>{countries.map(c=><option key={c}>{c}</option>)}</select></div></>}
      {step===3&&<><h2 className="text-xl font-black text-gray-900">Payments</h2><p className="mt-1 text-sm text-gray-500">Bazunk uses Stripe to process payments securely.</p><div className="mt-8 rounded-2xl border border-blue-100 bg-blue-50 p-6"><CreditCard className="h-9 w-9 text-[#3B4FD8]"/><h3 className="mt-3 font-black text-gray-900">No card details stored by Bazunk</h3><p className="mt-2 text-sm leading-6 text-gray-600">You can add or use a payment method securely during your first checkout. Bazunk does not ask you to type card details into this setup screen.</p><div className="mt-4 flex items-center gap-2 text-sm font-semibold text-emerald-700"><ShieldCheck className="h-4 w-4"/>Secure payment setup at checkout</div></div></>}
      {step===4&&<><h2 className="text-xl font-black text-gray-900">How will you use Bazunk?</h2><p className="mt-1 text-sm text-gray-500">You can change this later. Buyers can continue without setting up a business account.</p><div className="mt-6 space-y-3">{[["private","Private seller","Selling your own items occasionally"],["sole_trader","Sole trader","Selling as an individual business"],["business","Business","Selling for a company or organisation"]].map(([v,t,d])=><button key={v} onClick={()=>update("sellerType",v)} className={`w-full rounded-2xl border p-4 text-left ${p.sellerType===v?"border-[#4A5CE8] bg-[#4A5CE8]/5":"border-gray-200"}`}><div className="font-bold text-gray-900">{t}</div><div className="text-sm text-gray-500">{d}</div></button>)}</div></>}
      {step===5&&<><h2 className="text-xl font-black text-gray-900">Notifications</h2><p className="mt-1 text-sm text-gray-500">Choose what Bazunk should keep you informed about.</p><div className="mt-6 divide-y rounded-2xl border border-gray-200">{([['orders','Orders & delivery'],['offers','Offers & bids'],['messages','Messages'],['promotions','Bazunk news & promotions']] as const).map(([k,l])=><label key={k} className="flex items-center justify-between p-4 text-sm font-semibold text-gray-800"><span>{l}</span><input type="checkbox" className="h-5 w-5 accent-[#4A5CE8]" checked={p.notificationPreferences[k]} onChange={e=>update("notificationPreferences",{...p.notificationPreferences,[k]:e.target.checked})}/></label>)}</div></>}
      {step===6&&<div className="py-8 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100"><Check className="h-8 w-8 text-emerald-600"/></div><h2 className="mt-5 text-2xl font-black text-gray-900">You're ready for Bazunk</h2><p className="mx-auto mt-2 max-w-md text-sm text-gray-500">Your public identity is <b>@{p.username}</b>. Your private account details and address stay private.</p><div className="mx-auto mt-6 max-w-sm rounded-xl bg-gray-50 p-4 text-left text-sm"><div><b>Name:</b> {p.name}</div><div className="mt-1"><b>Username:</b> @{p.username}</div><div className="mt-1"><b>Seller type:</b> {p.sellerType.replace('_',' ')}</div></div></div>}
      {error&&<div className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
    </div>
    <div className="flex items-center justify-between border-t bg-gray-50 px-6 py-4">{step>1?<button disabled={saving} onClick={()=>{setError("");setStep(x=>x-1)}} className="flex items-center gap-1 rounded-xl px-4 py-2 text-sm font-bold text-gray-600"><ChevronLeft className="h-4 w-4"/>Back</button>:<span/>}<button disabled={saving} onClick={next} className="flex items-center gap-2 rounded-xl bg-[#4A5CE8] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Saving…":step===6?"Finish setup":"Save & continue"}{!saving&&step<6&&<ChevronRight className="h-4 w-4"/>}</button></div>
  </div></div>;
}
