import {useEffect,useState} from "react";
import {useAuth as useClerkAuth} from "@clerk/react";
import {CheckCircle2,Store} from "lucide-react";
export function ShopifyPublicImporter(){
 const{getToken}=useClerkAuth();const[url,setUrl]=useState(""),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<Record<string,boolean>>({}),[markup,setMarkup]=useState(20),[markupType,setMarkupType]=useState("percentage"),[category,setCategory]=useState("other"),[subcategory,setSubcategory]=useState(""),[sync,setSync]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const af=async(path:string,body:any)=>{const t=await getToken();return fetch(path,{method:"POST",headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})},body:JSON.stringify(body)})};
 const preview=async()=>{setBusy(true);setMsg("");setItems([]);setSelected({});try{const r=await af("/api/user/shopify-public/preview",{url});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load store");setItems(d.items||[]);setSelected(Object.fromEntries((d.items||[]).map((x:any)=>[x.sourceUrl,true])));setMsg(`Loaded ${d.items?.length||0} products from ${d.store}.`)}catch(e){setMsg(e instanceof Error?e.message:"Preview failed")}finally{setBusy(false)}};
 useEffect(()=>{const handoff=new URLSearchParams(window.location.search).get("handoff")||sessionStorage.getItem("bazunk_shopify_handoff");if(!handoff)return;try{if(handoff.length>18000)throw Error("Import batch too large");const data=JSON.parse(handoff);if(!Array.isArray(data.items)||data.items.length>100)throw Error("Invalid import batch");setItems(data.items);setSelected(Object.fromEntries(data.items.map((x:any)=>[x.sourceUrl,true])));setCategory(String(data.category||"other"));setSubcategory(String(data.subcategory||""));setMarkupType(data.markupType==="fixed"?"fixed":"percentage");setMarkup(Math.max(0,Number(data.markupValue)||0));setSync(data.syncEnabled!==false);setMsg("Shopify products transferred from Bazunk Data Platform. Review and click Import to publish.");sessionStorage.removeItem("bazunk_shopify_handoff");window.history.replaceState(null,"",window.location.pathname+"?source=shopify");}catch(e){setMsg(e instanceof Error?e.message:"Invalid Shopify import handoff")}},[]);
 const chosen=items.filter(x=>selected[x.sourceUrl]);
 const runImport=async()=>{if(!chosen.length)return;setBusy(true);setMsg("");try{const r=await af("/api/user/import-shopify-public",{items:chosen,category,subcategory,markupType,markupValue:markup,syncEnabled:sync});const d=await r.json();if(!r.ok)throw new Error(d.error||"Import failed");setMsg(d.message||"Import complete");}catch(e){setMsg(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}};
 return <div className="space-y-5"><div className="rounded-3xl border bg-white dark:bg-slate-900 p-6 shadow-sm"><div className="flex gap-3"><Store className="w-6 h-6 text-green-600"/><div className="flex-1"><h2 className="text-xl font-black">Import from Shopify URL</h2><p className="text-sm text-gray-500 mt-1">Paste a Shopify store, collection or product URL. No RapidAPI key required.</p><div className="flex flex-col sm:flex-row gap-2 mt-4"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://store.myshopify.com" className="flex-1 border rounded-xl px-3 py-2"/><button onClick={preview} disabled={busy||!url.trim()} className="px-5 py-2 rounded-xl bg-green-600 text-white font-black disabled:opacity-40">{busy?"Loading…":"Load products"}</button></div>{msg&&<p className="text-sm mt-3">{msg}</p>}</div></div></div>
 {items.length>0&&<div className="rounded-3xl border bg-white dark:bg-slate-900 p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">Choose products</h2><p className="text-sm text-gray-500">{chosen.length} of {items.length} selected</p></div><div className="flex gap-2"><button className="border rounded-lg px-3 py-2 text-sm font-bold" onClick={()=>setSelected(Object.fromEntries(items.map(x=>[x.sourceUrl,true])))}>Select all</button><button className="border rounded-lg px-3 py-2 text-sm font-bold" onClick={()=>setSelected({})}>Clear</button></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-5">{items.map(p=><label key={p.sourceUrl} className={`border rounded-2xl overflow-hidden cursor-pointer ${selected[p.sourceUrl]?"ring-2 ring-green-500":""}`}><div className="relative">{p.images?.[0]?.url?<img src={p.images[0].url} className="w-full h-40 object-cover"/>:<div className="h-40 bg-gray-100"/>}<input type="checkbox" className="absolute top-3 left-3 w-5 h-5" checked={!!selected[p.sourceUrl]} onChange={e=>setSelected({...selected,[p.sourceUrl]:e.target.checked})}/></div><div className="p-3"><b className="line-clamp-2">{p.title}</b><p className="text-sm text-gray-500 mt-1">{p.price?.currency} {Number(p.price?.amount||0).toFixed(2)} · {p.availability==="in_stock"?"In stock":"Out of stock"}</p></div></label>)}</div><div className="grid md:grid-cols-4 gap-3 mt-6"><label className="text-sm font-bold">Markup<select value={markupType} onChange={e=>setMarkupType(e.target.value)} className="block w-full border rounded-xl px-3 py-2 mt-1"><option value="percentage">Percentage %</option><option value="fixed">Fixed amount in source currency</option></select><input type="number" min="0" value={markup} onChange={e=>setMarkup(Math.max(0,Number(e.target.value)))} className="block w-full border rounded-xl px-3 py-2 mt-1"/></label><label className="text-sm font-bold">Category<input value={category} onChange={e=>setCategory(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))} className="block w-full border rounded-xl px-3 py-2 mt-1"/></label><label className="text-sm font-bold">Subcategory<input value={subcategory} onChange={e=>setSubcategory(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-"))} className="block w-full border rounded-xl px-3 py-2 mt-1"/></label><label className="text-sm font-bold flex items-center gap-2 pt-6"><input type="checkbox" checked={sync} onChange={e=>setSync(e.target.checked)}/> Enable source sync</label></div><button onClick={runImport} disabled={busy||!chosen.length||!category} className="mt-5 px-6 py-3 rounded-xl bg-indigo-600 text-white font-black disabled:opacity-40">{busy?"Importing…":`Import ${chosen.length} to Bazunk`}</button>{msg.toLowerCase().includes("imported")&&<p className="mt-3 text-green-700 font-bold"><CheckCircle2 className="inline w-4 h-4 mr-1"/>{msg}</p>}</div>}</div>
}
