kind = "web"
previewPath = "/"
title = "Bazunk"
version = "1.0.0"
id = "artifacts/sellbuydeal"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18918

[services.development]
run = "pnpm --filter @workspace/sellbuydeal run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sellbuydeal", "run", "build" ]
publicDir = "artifacts/sellbuydeal/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18918"
BASE_PATH = "/"
