// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icon-styles/Filled.tsx": () => import("../components/mockups/icon-styles/Filled.tsx"),
  "./components/mockups/icon-styles/Gradient.tsx": () => import("../components/mockups/icon-styles/Gradient.tsx"),
  "./components/mockups/icon-styles/Tonal.tsx": () => import("../components/mockups/icon-styles/Tonal.tsx")
};
