import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type LanguageCode = "en" | "de" | "fr" | "es" | "it" | "pt" | "nl";

export const LANGUAGES: Record<LanguageCode, { code: LanguageCode; name: string; nativeName: string }> = {
  en: { code: "en", name: "English", nativeName: "English", electronics:"Electronics", fashion:"Fashion", gaming:"Gaming", homeGarden:"Home & Garden", sports:"Sports", books:"Books", collectibles:"Collectibles", automotive:"Automotive", allCategories:"All Categories", shopNow:"Shop Now", featuredListings:"Featured Listings", trendingToday:"Trending Today", promotedListings:"Promoted Listings", homepageSpotlight:"Homepage Spotlight", browseAll:"Browse All", browseAllListings:"Browse All Listings", createListing:"Create Your Listing", fillDetails:"Fill in the details below to list your item", basicInformation:"Basic Information", title:"Title", currencyPrice:"Currency & Price", category:"Category", selectCategory:"Select category", photos:"Photos", descriptionField:"Description", shipping:"Shipping", quantity:"Quantity", publishListing:"Publish Listing", saveDraft:"Save Draft", price:"Price", filters:"Filters", sortBy:"Sort by", results:"results" },
  de: { code: "de", name: "German", nativeName: "Deutsch", electronics:"Elektronik", fashion:"Mode", gaming:"Gaming", homeGarden:"Haus & Garten", sports:"Sport", books:"Bücher", collectibles:"Sammlerstücke", automotive:"Auto", allCategories:"Alle Kategorien", shopNow:"Jetzt shoppen", featuredListings:"Empfohlene Angebote", trendingToday:"Heute im Trend", promotedListings:"Beworbene Angebote", homepageSpotlight:"Homepage-Spotlight", browseAll:"Alle ansehen", browseAllListings:"Alle Angebote ansehen", createListing:"Angebot erstellen", fillDetails:"Fülle die Details aus, um deinen Artikel anzubieten", basicInformation:"Grundinformationen", title:"Titel", currencyPrice:"Währung & Preis", category:"Kategorie", selectCategory:"Kategorie wählen", photos:"Fotos", descriptionField:"Beschreibung", shipping:"Versand", quantity:"Menge", publishListing:"Angebot veröffentlichen", saveDraft:"Entwurf speichern", price:"Preis", filters:"Filter", sortBy:"Sortieren nach", results:"Ergebnisse" },
  fr: { code: "fr", name: "French", nativeName: "Français", electronics:"Électronique", fashion:"Mode", gaming:"Jeux vidéo", homeGarden:"Maison & jardin", sports:"Sports", books:"Livres", collectibles:"Objets de collection", automotive:"Automobile", allCategories:"Toutes les catégories", shopNow:"Acheter", featuredListings:"Annonces en vedette", trendingToday:"Tendances du jour", promotedListings:"Annonces sponsorisées", homepageSpotlight:"À la une", browseAll:"Tout voir", browseAllListings:"Voir toutes les annonces", createListing:"Créer une annonce", fillDetails:"Remplissez les informations pour mettre votre article en vente", basicInformation:"Informations de base", title:"Titre", currencyPrice:"Devise et prix", category:"Catégorie", selectCategory:"Choisir une catégorie", photos:"Photos", descriptionField:"Description", shipping:"Livraison", quantity:"Quantité", publishListing:"Publier l’annonce", saveDraft:"Enregistrer le brouillon", price:"Prix", filters:"Filtres", sortBy:"Trier par", results:"résultats" },
  es: { code: "es", name: "Spanish", nativeName: "Español", electronics:"Electrónica", fashion:"Moda", gaming:"Videojuegos", homeGarden:"Hogar y jardín", sports:"Deportes", books:"Libros", collectibles:"Coleccionables", automotive:"Motor", allCategories:"Todas las categorías", shopNow:"Comprar ahora", featuredListings:"Anuncios destacados", trendingToday:"Tendencias de hoy", promotedListings:"Anuncios promocionados", homepageSpotlight:"Destacados", browseAll:"Ver todo", browseAllListings:"Ver todos los anuncios", createListing:"Crear anuncio", fillDetails:"Completa los datos para publicar tu artículo", basicInformation:"Información básica", title:"Título", currencyPrice:"Moneda y precio", category:"Categoría", selectCategory:"Seleccionar categoría", photos:"Fotos", descriptionField:"Descripción", shipping:"Envío", quantity:"Cantidad", publishListing:"Publicar anuncio", saveDraft:"Guardar borrador", price:"Precio", filters:"Filtros", sortBy:"Ordenar por", results:"resultados" },
  it: { code: "it", name: "Italian", nativeName: "Italiano", electronics:"Elettronica", fashion:"Moda", gaming:"Gaming", homeGarden:"Casa e giardino", sports:"Sport", books:"Libri", collectibles:"Collezionismo", automotive:"Auto", allCategories:"Tutte le categorie", shopNow:"Acquista ora", featuredListings:"Annunci in evidenza", trendingToday:"Di tendenza oggi", promotedListings:"Annunci promossi", homepageSpotlight:"In primo piano", browseAll:"Vedi tutto", browseAllListings:"Vedi tutti gli annunci", createListing:"Crea annuncio", fillDetails:"Inserisci i dettagli per mettere in vendita il tuo articolo", basicInformation:"Informazioni di base", title:"Titolo", currencyPrice:"Valuta e prezzo", category:"Categoria", selectCategory:"Seleziona categoria", photos:"Foto", descriptionField:"Descrizione", shipping:"Spedizione", quantity:"Quantità", publishListing:"Pubblica annuncio", saveDraft:"Salva bozza", price:"Prezzo", filters:"Filtri", sortBy:"Ordina per", results:"risultati" },
  pt: { code: "pt", name: "Portuguese", nativeName: "Português", electronics:"Eletrónica", fashion:"Moda", gaming:"Jogos", homeGarden:"Casa e jardim", sports:"Desporto", books:"Livros", collectibles:"Colecionáveis", automotive:"Automóvel", allCategories:"Todas as categorias", shopNow:"Comprar agora", featuredListings:"Anúncios em destaque", trendingToday:"Tendências de hoje", promotedListings:"Anúncios promovidos", homepageSpotlight:"Destaque", browseAll:"Ver tudo", browseAllListings:"Ver todos os anúncios", createListing:"Criar anúncio", fillDetails:"Preencha os detalhes para anunciar o seu artigo", basicInformation:"Informações básicas", title:"Título", currencyPrice:"Moeda e preço", category:"Categoria", selectCategory:"Selecionar categoria", photos:"Fotos", descriptionField:"Descrição", shipping:"Envio", quantity:"Quantidade", publishListing:"Publicar anúncio", saveDraft:"Guardar rascunho", price:"Preço", filters:"Filtros", sortBy:"Ordenar por", results:"resultados" },
  nl: { code: "nl", name: "Dutch", nativeName: "Nederlands", electronics:"Elektronica", fashion:"Mode", gaming:"Gaming", homeGarden:"Huis & tuin", sports:"Sport", books:"Boeken", collectibles:"Verzamelobjecten", automotive:"Auto", allCategories:"Alle categorieën", shopNow:"Nu winkelen", featuredListings:"Uitgelichte advertenties", trendingToday:"Vandaag populair", promotedListings:"Gepromote advertenties", homepageSpotlight:"Homepage spotlight", browseAll:"Alles bekijken", browseAllListings:"Alle advertenties bekijken", createListing:"Advertentie maken", fillDetails:"Vul de gegevens in om je artikel te verkopen", basicInformation:"Basisinformatie", title:"Titel", currencyPrice:"Valuta & prijs", category:"Categorie", selectCategory:"Categorie kiezen", photos:"Foto's", descriptionField:"Beschrijving", shipping:"Verzending", quantity:"Aantal", publishListing:"Advertentie plaatsen", saveDraft:"Concept opslaan", price:"Prijs", filters:"Filters", sortBy:"Sorteren op", results:"resultaten" },
};

export const COUNTRY_LANGUAGE_MAP: Record<string, LanguageCode> = {
  GB: "en", US: "en", IE: "en", AU: "en", CA: "en", NZ: "en", CH: "de",
  DE: "de", AT: "de", FR: "fr", LU: "fr", IT: "it", ES: "es", PT: "pt",
  NL: "nl", BE: "nl", FI: "en", GR: "en",
};

const translations: Record<LanguageCode, Record<string, string>> = {
  en: { country:"Country", currency:"Currency", language:"Language", browse:"Browse", categories:"Categories", live:"Live", rewards:"Rewards", search:"Search listings…", home:"Home", auctions:"Auctions", flashSales:"Flash Sales", classifieds:"Classifieds", directSale:"Direct Sale", buyerProtection:"Buyer Protection", support:"Support", messages:"Messages", dashboard:"Dashboard", signIn:"Sign In", joinFree:"Join Free", shipsFrom:"Ships from", shipsTo:"Ships to", deliveryLocation:"Delivery & location", condition:"Condition", available:"Available", listingCurrency:"Listing currency", descriptionDetails:"Description & Details", description:"Description", itemDetails:"Item Details", buyNow:"Buy It Now", makeOffer:"Make an Offer", messageSeller:"Message Seller" },
  de: { country:"Land", currency:"Währung", language:"Sprache", browse:"Stöbern", categories:"Kategorien", live:"Live", rewards:"Prämien", search:"Angebote suchen…", home:"Startseite", auctions:"Auktionen", flashSales:"Blitzangebote", classifieds:"Kleinanzeigen", directSale:"Direktverkauf", buyerProtection:"Käuferschutz", support:"Hilfe", messages:"Nachrichten", dashboard:"Übersicht", signIn:"Anmelden", joinFree:"Kostenlos registrieren", shipsFrom:"Versand aus", shipsTo:"Versand nach", deliveryLocation:"Lieferung & Standort", condition:"Zustand", available:"Verfügbar", listingCurrency:"Angebotswährung", descriptionDetails:"Beschreibung & Details", description:"Beschreibung", itemDetails:"Artikeldetails", buyNow:"Sofort kaufen", makeOffer:"Preis vorschlagen", messageSeller:"Verkäufer kontaktieren" },
  fr: { country:"Pays", currency:"Devise", language:"Langue", browse:"Parcourir", categories:"Catégories", live:"En direct", rewards:"Récompenses", search:"Rechercher des annonces…", home:"Accueil", auctions:"Enchères", flashSales:"Ventes flash", classifieds:"Petites annonces", directSale:"Vente directe", buyerProtection:"Protection acheteur", support:"Aide", messages:"Messages", dashboard:"Tableau de bord", signIn:"Se connecter", joinFree:"Inscription gratuite", shipsFrom:"Expédié depuis", shipsTo:"Expédié vers", deliveryLocation:"Livraison et localisation", condition:"État", available:"Disponible", listingCurrency:"Devise de l’annonce", descriptionDetails:"Description et détails", description:"Description", itemDetails:"Détails de l’article", buyNow:"Acheter maintenant", makeOffer:"Faire une offre", messageSeller:"Contacter le vendeur" },
  es: { country:"País", currency:"Moneda", language:"Idioma", browse:"Explorar", categories:"Categorías", live:"En directo", rewards:"Recompensas", search:"Buscar anuncios…", home:"Inicio", auctions:"Subastas", flashSales:"Ofertas flash", classifieds:"Clasificados", directSale:"Venta directa", buyerProtection:"Protección del comprador", support:"Ayuda", messages:"Mensajes", dashboard:"Panel", signIn:"Iniciar sesión", joinFree:"Registrarse gratis", shipsFrom:"Se envía desde", shipsTo:"Se envía a", deliveryLocation:"Entrega y ubicación", condition:"Estado", available:"Disponible", listingCurrency:"Moneda del anuncio", descriptionDetails:"Descripción y detalles", description:"Descripción", itemDetails:"Detalles del artículo", buyNow:"Comprar ahora", makeOffer:"Hacer una oferta", messageSeller:"Contactar al vendedor" },
  it: { country:"Paese", currency:"Valuta", language:"Lingua", browse:"Esplora", categories:"Categorie", live:"Live", rewards:"Premi", search:"Cerca annunci…", home:"Home", auctions:"Aste", flashSales:"Vendite lampo", classifieds:"Annunci", directSale:"Vendita diretta", buyerProtection:"Protezione acquirenti", support:"Assistenza", messages:"Messaggi", dashboard:"Dashboard", signIn:"Accedi", joinFree:"Registrati gratis", shipsFrom:"Spedito da", shipsTo:"Spedito a", deliveryLocation:"Consegna e località", condition:"Condizione", available:"Disponibile", listingCurrency:"Valuta dell’annuncio", descriptionDetails:"Descrizione e dettagli", description:"Descrizione", itemDetails:"Dettagli articolo", buyNow:"Compra subito", makeOffer:"Fai un’offerta", messageSeller:"Contatta il venditore" },
  pt: { country:"País", currency:"Moeda", language:"Idioma", browse:"Explorar", categories:"Categorias", live:"Ao vivo", rewards:"Recompensas", search:"Pesquisar anúncios…", home:"Início", auctions:"Leilões", flashSales:"Ofertas relâmpago", classifieds:"Classificados", directSale:"Venda direta", buyerProtection:"Proteção do comprador", support:"Ajuda", messages:"Mensagens", dashboard:"Painel", signIn:"Entrar", joinFree:"Registo grátis", shipsFrom:"Enviado de", shipsTo:"Enviado para", deliveryLocation:"Entrega e localização", condition:"Condição", available:"Disponível", listingCurrency:"Moeda do anúncio", descriptionDetails:"Descrição e detalhes", description:"Descrição", itemDetails:"Detalhes do artigo", buyNow:"Comprar agora", makeOffer:"Fazer oferta", messageSeller:"Contactar vendedor" },
  nl: { country:"Land", currency:"Valuta", language:"Taal", browse:"Bladeren", categories:"Categorieën", live:"Live", rewards:"Beloningen", search:"Advertenties zoeken…", home:"Home", auctions:"Veilingen", flashSales:"Flitsverkopen", classifieds:"Advertenties", directSale:"Directe verkoop", buyerProtection:"Kopersbescherming", support:"Help", messages:"Berichten", dashboard:"Dashboard", signIn:"Inloggen", joinFree:"Gratis aanmelden", shipsFrom:"Verzonden vanuit", shipsTo:"Verzonden naar", deliveryLocation:"Levering en locatie", condition:"Conditie", available:"Beschikbaar", listingCurrency:"Advertentievaluta", descriptionDetails:"Beschrijving en details", description:"Beschrijving", itemDetails:"Artikelgegevens", buyNow:"Nu kopen", makeOffer:"Bod doen", messageSeller:"Verkoper berichten" },
};

type LanguageContextType = {
  language: typeof LANGUAGES[LanguageCode];
  setLanguage: (code: LanguageCode) => void;
  setLanguageForCountry: (countryCode: string) => void;
  t: (key: string, fallback?: string) => string;
};

const LanguageContext = createContext<LanguageContextType | null>(null);
const STORAGE_KEY = "sbd_language";
const MANUAL_KEY = "sbd_language_manual";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [code, setCode] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as LanguageCode | null;
      if (saved && saved in LANGUAGES) return saved;
      const browser = (navigator.language || "en").slice(0, 2) as LanguageCode;
      return browser in LANGUAGES ? browser : "en";
    } catch { return "en"; }
  });
  const setLanguage = (next: LanguageCode) => { setCode(next); try { localStorage.setItem(STORAGE_KEY, next); localStorage.setItem(MANUAL_KEY, "1"); } catch {} };
  const setLanguageForCountry = (countryCode: string) => {
    try { if (localStorage.getItem(MANUAL_KEY) === "1") return; } catch {}
    const next = COUNTRY_LANGUAGE_MAP[countryCode] || "en"; setCode(next); try { localStorage.setItem(STORAGE_KEY, next); } catch {}
  };
  useEffect(() => { document.documentElement.lang = code; }, [code]);
  const value = useMemo(() => ({ language: LANGUAGES[code], setLanguage, setLanguageForCountry, t: (key: string, fallback?: string) => translations[code][key] || translations.en[key] || fallback || key }), [code]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage() { const ctx = useContext(LanguageContext); if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider"); return ctx; }
